"""autogenerated by genpy from clm_bridge/ClmHead.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import clm_bridge.msg

class ClmHead(genpy.Message):
  _md5sum = "c12d2399ec432b3f3472148f0d506a8b"
  _type = "clm_bridge/ClmHead"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 detection_success
float32 detection_confidence
float32 time_stamp 

clm_bridge/ClmHeadPose headpose
clm_bridge/ClmEyeGaze[] eyegazes
clm_bridge/ClmFacialActionUnit[] aus
================================================================================
MSG: clm_bridge/ClmHeadPose
float32 pitch
float32 yaw
float32 roll
float32 x
float32 y
float32 z
================================================================================
MSG: clm_bridge/ClmEyeGaze
uint8 RIGHT_EYE = 0
uint8 LEFT_EYE = 1

uint8 eye_id

float32 gaze_direction_cameraref_x
float32 gaze_direction_cameraref_y
float32 gaze_direction_cameraref_z

float32 gaze_direction_headref_x
float32 gaze_direction_headref_y
float32 gaze_direction_headref_z
================================================================================
MSG: clm_bridge/ClmFacialActionUnit
uint8 AU_TYPE_AU01_INNER_BROW_RAISER = 1
uint8 AU_TYPE_AU02_OUTER_BROW_RAISER = 2
uint8 AU_TYPE_AU04_BROW_LOWERER = 4
uint8 AU_TYPE_AU05_UPPER_LID_RAISER = 5
uint8 AU_TYPE_AU06_CHEEK_RAISER = 6
uint8 AU_TYPE_AU09_NOSE_WRINKLER = 9
uint8 AU_TYPE_AU10_UPPER_LIP_RAISER = 10
uint8 AU_TYPE_AU12_LIP_CORNER_PULLER = 12
uint8 AU_TYPE_AU14_DIMPLER = 14
uint8 AU_TYPE_AU15_LIP_CORNER_DEPRESSOR = 15
uint8 AU_TYPE_AU17_CHIN_RAISER = 17
uint8 AU_TYPE_AU20_LIP_STRETCHER = 20
uint8 AU_TYPE_AU23_LIP_LIGHTENER = 23 
uint8 AU_TYPE_AU25_LIPS_PART = 25
uint8 AU_TYPE_AU26_JAW_DROP = 26
uint8 AU_TYPE_AU28_LIP_SUCK = 28
uint8 AU_TYPE_AU45_BLINK = 45

uint8 AU_PREDICTION_METHOD_REGRESSION = 0
uint8 AU_PREDICTION_METHOD_CLASSIFICATION = 1

float32 value
uint8 au_type
uint8 au_prediction_method
"""
  __slots__ = ['detection_success','detection_confidence','time_stamp','headpose','eyegazes','aus']
  _slot_types = ['uint8','float32','float32','clm_bridge/ClmHeadPose','clm_bridge/ClmEyeGaze[]','clm_bridge/ClmFacialActionUnit[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       detection_success,detection_confidence,time_stamp,headpose,eyegazes,aus

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ClmHead, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.detection_success is None:
        self.detection_success = 0
      if self.detection_confidence is None:
        self.detection_confidence = 0.
      if self.time_stamp is None:
        self.time_stamp = 0.
      if self.headpose is None:
        self.headpose = clm_bridge.msg.ClmHeadPose()
      if self.eyegazes is None:
        self.eyegazes = []
      if self.aus is None:
        self.aus = []
    else:
      self.detection_success = 0
      self.detection_confidence = 0.
      self.time_stamp = 0.
      self.headpose = clm_bridge.msg.ClmHeadPose()
      self.eyegazes = []
      self.aus = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B8f.pack(_x.detection_success, _x.detection_confidence, _x.time_stamp, _x.headpose.pitch, _x.headpose.yaw, _x.headpose.roll, _x.headpose.x, _x.headpose.y, _x.headpose.z))
      length = len(self.eyegazes)
      buff.write(_struct_I.pack(length))
      for val1 in self.eyegazes:
        _x = val1
        buff.write(_struct_B6f.pack(_x.eye_id, _x.gaze_direction_cameraref_x, _x.gaze_direction_cameraref_y, _x.gaze_direction_cameraref_z, _x.gaze_direction_headref_x, _x.gaze_direction_headref_y, _x.gaze_direction_headref_z))
      length = len(self.aus)
      buff.write(_struct_I.pack(length))
      for val1 in self.aus:
        _x = val1
        buff.write(_struct_f2B.pack(_x.value, _x.au_type, _x.au_prediction_method))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.headpose is None:
        self.headpose = clm_bridge.msg.ClmHeadPose()
      if self.eyegazes is None:
        self.eyegazes = None
      if self.aus is None:
        self.aus = None
      end = 0
      _x = self
      start = end
      end += 33
      (_x.detection_success, _x.detection_confidence, _x.time_stamp, _x.headpose.pitch, _x.headpose.yaw, _x.headpose.roll, _x.headpose.x, _x.headpose.y, _x.headpose.z,) = _struct_B8f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.eyegazes = []
      for i in range(0, length):
        val1 = clm_bridge.msg.ClmEyeGaze()
        _x = val1
        start = end
        end += 25
        (_x.eye_id, _x.gaze_direction_cameraref_x, _x.gaze_direction_cameraref_y, _x.gaze_direction_cameraref_z, _x.gaze_direction_headref_x, _x.gaze_direction_headref_y, _x.gaze_direction_headref_z,) = _struct_B6f.unpack(str[start:end])
        self.eyegazes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.aus = []
      for i in range(0, length):
        val1 = clm_bridge.msg.ClmFacialActionUnit()
        _x = val1
        start = end
        end += 6
        (_x.value, _x.au_type, _x.au_prediction_method,) = _struct_f2B.unpack(str[start:end])
        self.aus.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B8f.pack(_x.detection_success, _x.detection_confidence, _x.time_stamp, _x.headpose.pitch, _x.headpose.yaw, _x.headpose.roll, _x.headpose.x, _x.headpose.y, _x.headpose.z))
      length = len(self.eyegazes)
      buff.write(_struct_I.pack(length))
      for val1 in self.eyegazes:
        _x = val1
        buff.write(_struct_B6f.pack(_x.eye_id, _x.gaze_direction_cameraref_x, _x.gaze_direction_cameraref_y, _x.gaze_direction_cameraref_z, _x.gaze_direction_headref_x, _x.gaze_direction_headref_y, _x.gaze_direction_headref_z))
      length = len(self.aus)
      buff.write(_struct_I.pack(length))
      for val1 in self.aus:
        _x = val1
        buff.write(_struct_f2B.pack(_x.value, _x.au_type, _x.au_prediction_method))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.headpose is None:
        self.headpose = clm_bridge.msg.ClmHeadPose()
      if self.eyegazes is None:
        self.eyegazes = None
      if self.aus is None:
        self.aus = None
      end = 0
      _x = self
      start = end
      end += 33
      (_x.detection_success, _x.detection_confidence, _x.time_stamp, _x.headpose.pitch, _x.headpose.yaw, _x.headpose.roll, _x.headpose.x, _x.headpose.y, _x.headpose.z,) = _struct_B8f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.eyegazes = []
      for i in range(0, length):
        val1 = clm_bridge.msg.ClmEyeGaze()
        _x = val1
        start = end
        end += 25
        (_x.eye_id, _x.gaze_direction_cameraref_x, _x.gaze_direction_cameraref_y, _x.gaze_direction_cameraref_z, _x.gaze_direction_headref_x, _x.gaze_direction_headref_y, _x.gaze_direction_headref_z,) = _struct_B6f.unpack(str[start:end])
        self.eyegazes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.aus = []
      for i in range(0, length):
        val1 = clm_bridge.msg.ClmFacialActionUnit()
        _x = val1
        start = end
        end += 6
        (_x.value, _x.au_type, _x.au_prediction_method,) = _struct_f2B.unpack(str[start:end])
        self.aus.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_f2B = struct.Struct("<f2B")
_struct_B6f = struct.Struct("<B6f")
_struct_B8f = struct.Struct("<B8f")
